# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-14 06:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0006_auto_20180322_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_info',
            fields=[
                ('company_Num', models.IntegerField(primary_key=True, serialize=False)),
                ('company_Name', models.CharField(max_length=20)),
                ('company_Scale', models.CharField(max_length=20)),
                ('jobCode', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Company_select',
            fields=[
                ('comp_selNum', models.IntegerField(primary_key=True, serialize=False)),
                ('company_Num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Company_info')),
            ],
        ),
        migrations.CreateModel(
            name='Employee_form',
            fields=[
                ('emplo_fNum', models.IntegerField(primary_key=True, serialize=False)),
                ('emploF_info', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Interview_apply',
            fields=[
                ('inter_apply_num', models.IntegerField(primary_key=True, serialize=False)),
                ('work', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Interview_state',
            fields=[
                ('interv_sNum', models.IntegerField(primary_key=True, serialize=False)),
                ('intervS_info', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Member_info',
            fields=[
                ('mem_Num', models.IntegerField(primary_key=True, serialize=False)),
                ('mem_ID', models.CharField(max_length=20)),
                ('mem_PW', models.CharField(max_length=20)),
                ('mem_Gender', models.CharField(max_length=2)),
                ('mem_Birth', models.CharField(max_length=10)),
                ('mem_HP', models.CharField(max_length=20)),
                ('mem_Email', models.CharField(max_length=50)),
                ('mem_Add', models.CharField(max_length=200)),
                ('mem_Name', models.CharField(max_length=20)),
                ('mem_Rank', models.CharField(max_length=10)),
                ('mem_DIV', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Member_occupation',
            fields=[
                ('mem_occ_Num', models.IntegerField(primary_key=True, serialize=False)),
                ('mem_Num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Member_info')),
            ],
        ),
        migrations.CreateModel(
            name='Mento_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_Pic', models.ImageField(upload_to='')),
                ('mento_Career', models.CharField(max_length=2000)),
                ('mento_Proof_doc', models.FileField(upload_to='')),
                ('mem_Num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Member_info')),
            ],
        ),
        migrations.CreateModel(
            name='Occupation_type',
            fields=[
                ('occ_Num', models.IntegerField(primary_key=True, serialize=False)),
                ('occ_Name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Self_introduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_intro_cont', models.CharField(max_length=2000)),
                ('portfolio_File', models.FileField(upload_to='')),
                ('inter_occupation1', models.CharField(max_length=20)),
                ('inter_occupation2', models.CharField(max_length=20)),
                ('inter_occupation3', models.CharField(max_length=20)),
                ('mem_Num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Member_info')),
            ],
        ),
        migrations.AddField(
            model_name='member_occupation',
            name='occ_Num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Occupation_type'),
        ),
        migrations.AddField(
            model_name='interview_apply',
            name='comp_selNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Interview_state'),
        ),
        migrations.AddField(
            model_name='interview_apply',
            name='emplo_fNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Employee_form'),
        ),
        migrations.AddField(
            model_name='interview_apply',
            name='interv_sNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Company_select'),
        ),
        migrations.AddField(
            model_name='company_select',
            name='mem_Num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Member_info'),
        ),
    ]
