# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-14 06:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_auto_20180514_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_num', models.IntegerField()),
                ('b_title', models.CharField(max_length=20)),
                ('b_contnet', models.CharField(max_length=500)),
                ('b_date', models.DateField(null=True)),
                ('b_hit', models.IntegerField(blank=True, default=0, null=True)),
                ('b_parent_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Board_C',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_categ', models.IntegerField()),
                ('b_categ_name', models.CharField(max_length=20)),
                ('board_c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Board')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_num', models.IntegerField()),
                ('l_date', models.DateField(null=True)),
                ('like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Member_info')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_num', models.IntegerField()),
                ('mrapply_num', models.IntegerField()),
                ('men_num', models.IntegerField()),
                ('mr_title', models.CharField(max_length=20)),
                ('mto_name', models.CharField(max_length=20)),
                ('r_score', models.IntegerField()),
                ('r_content', models.CharField(max_length=500)),
                ('r_image', models.ImageField(upload_to='')),
                ('r_like', models.IntegerField(blank=True, default=0, null=True)),
                ('r_date', models.DateField(null=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Member_info')),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Board_C'),
        ),
    ]
