# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-14 14:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0008_auto_20180514_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biz_Wish',
            fields=[
                ('biz_wish_num', models.IntegerField(primary_key=True, serialize=False)),
                ('mem_Num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Member_info')),
            ],
        ),
        migrations.CreateModel(
            name='Inter',
            fields=[
                ('inter_num', models.IntegerField(primary_key=True, serialize=False)),
                ('inter_pay_method', models.CharField(max_length=10)),
                ('inter_credit_com', models.CharField(max_length=10)),
                ('inter_credit_num', models.IntegerField()),
                ('inter_apporve_num', models.IntegerField()),
                ('inter_approve_date', models.DateTimeField(auto_now_add=True)),
                ('inter_depositless_name', models.CharField(max_length=10)),
                ('inter_depositless_date', models.DateTimeField(auto_now_add=True)),
                ('inter_depositless_bank', models.CharField(max_length=10)),
                ('inter_deposit_date', models.DateTimeField(auto_now_add=True)),
                ('inter_payamount', models.IntegerField()),
                ('inter_apply_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Interview_apply')),
            ],
        ),
        migrations.CreateModel(
            name='Mr_Wish',
            fields=[
                ('mr_wish_num', models.IntegerField(primary_key=True, serialize=False)),
                ('mem_Num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Member_info')),
            ],
        ),
        migrations.CreateModel(
            name='Mrapply',
            fields=[
                ('mrapply_num', models.IntegerField(primary_key=True, serialize=False)),
                ('mrapply_start', models.DateTimeField(auto_now_add=True)),
                ('mrapply_con', models.IntegerField()),
                ('mr_pay_method', models.CharField(max_length=10)),
                ('mr_credit_com', models.CharField(max_length=10)),
                ('mr_credit_num', models.IntegerField()),
                ('mr_apporve_num', models.IntegerField()),
                ('mr_approve_date', models.DateTimeField(auto_now_add=True)),
                ('mr_depositless_name', models.CharField(max_length=10)),
                ('mr_depositless_date', models.DateTimeField(auto_now_add=True)),
                ('mr_depositless_bank', models.CharField(max_length=10)),
                ('mr_deposit_date', models.DateTimeField(auto_now_add=True)),
                ('mr_payamount', models.IntegerField()),
                ('mr_wish_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Mr_Wish')),
            ],
        ),
        migrations.CreateModel(
            name='Mrapply_State',
            fields=[
                ('mrapply_con', models.IntegerField(primary_key=True, serialize=False)),
                ('mrapply_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Mtr_daily_report',
            fields=[
                ('mtr_daily_num', models.IntegerField(primary_key=True, serialize=False)),
                ('mtr_lesson', models.CharField(blank=True, max_length=500, null=True)),
                ('mtr_date', models.DateField(auto_now_add=True)),
                ('mtr_answer', models.CharField(blank=True, max_length=500, null=True)),
                ('mtr_content', models.CharField(blank=True, max_length=500, null=True)),
                ('mrapply_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Mrapply')),
            ],
        ),
        migrations.CreateModel(
            name='Mtr_info',
            fields=[
                ('mtr_num', models.IntegerField(primary_key=True, serialize=False)),
                ('field', models.CharField(blank=True, max_length=500, null=True)),
                ('theme', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.IntegerField()),
                ('mtr_content', models.CharField(blank=True, max_length=500, null=True)),
                ('fixed_people', models.IntegerField()),
                ('mem_Num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Mento_info')),
            ],
        ),
        migrations.RemoveField(
            model_name='like',
            name='like',
        ),
        migrations.RenameField(
            model_name='board',
            old_name='b_parent_id',
            new_name='b_categ_num',
        ),
        migrations.RemoveField(
            model_name='board',
            name='b_date',
        ),
        migrations.RemoveField(
            model_name='board',
            name='b_num',
        ),
        migrations.RemoveField(
            model_name='board',
            name='board',
        ),
        migrations.RemoveField(
            model_name='board_c',
            name='b_categ',
        ),
        migrations.RemoveField(
            model_name='board_c',
            name='board_c',
        ),
        migrations.RemoveField(
            model_name='board_c',
            name='id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='men_num',
        ),
        migrations.RemoveField(
            model_name='review',
            name='mrapply_num',
        ),
        migrations.RemoveField(
            model_name='review',
            name='review',
        ),
        migrations.AddField(
            model_name='board',
            name='b_published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='board_c',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='team.Board_C'),
        ),
        migrations.AddField(
            model_name='board',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='board_c',
            name='b_categ_num',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='mrapply_Num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='b_hit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='mr_title',
            field=models.CharField(max_length=20, null=True, verbose_name='멘티이름'),
        ),
        migrations.AlterField(
            model_name='review',
            name='mto_name',
            field=models.CharField(max_length=20, null=True, verbose_name='멘토이름'),
        ),
        migrations.AlterField(
            model_name='review',
            name='r_content',
            field=models.CharField(max_length=500, null=True, verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='review',
            name='r_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='작성날짜'),
        ),
        migrations.AlterField(
            model_name='review',
            name='r_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='review',
            name='r_like',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='좋아요 수'),
        ),
        migrations.AlterField(
            model_name='review',
            name='r_num',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='r_score',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='조회수'),
        ),
        migrations.AlterField(
            model_name='self_introduction',
            name='inter_occupation2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='self_introduction',
            name='inter_occupation3',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.AddField(
            model_name='mr_wish',
            name='mtr_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Mtr_info'),
        ),
    ]
