# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-15 05:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0009_auto_20180514_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biz_wish',
            name='mem_Num',
        ),
        migrations.AlterField(
            model_name='board',
            name='board_c',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='team.Board_C'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inter',
            name='inter_apporve_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='inter',
            name='inter_credit_com',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='inter',
            name='inter_credit_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='inter',
            name='inter_depositless_bank',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='inter',
            name='inter_depositless_name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mrapply',
            name='mr_apporve_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mrapply',
            name='mr_credit_com',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mrapply',
            name='mr_credit_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mrapply',
            name='mr_depositless_bank',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mrapply',
            name='mr_depositless_name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Biz_Wish',
        ),
    ]
