# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-15 08:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0011_auto_20180515_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_form',
            old_name='emploF_info',
            new_name='emplof_info',
        ),
        migrations.RenameField(
            model_name='interview_state',
            old_name='intervS_info',
            new_name='intervs_info',
        ),
        migrations.RemoveField(
            model_name='company_info',
            name='jobCode',
        ),
        migrations.AddField(
            model_name='company_info',
            name='jobcode',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='board',
            name='b_published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interview_apply',
            name='comp_selnum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Company_select'),
        ),
        migrations.AlterField(
            model_name='interview_apply',
            name='interv_snum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='team.Interview_state'),
        ),
        migrations.AlterField(
            model_name='review',
            name='mr_title',
            field=models.CharField(max_length=20, null=True, verbose_name='멘티이름'),
        ),
    ]
