# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-15 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0012_auto_20180515_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='self_introduction',
            name='inter_occupation1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Occupation_type'),
        ),
        migrations.AlterField(
            model_name='self_introduction',
            name='inter_occupation2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inter_occupation1', to='team.Occupation_type'),
        ),
        migrations.AlterField(
            model_name='self_introduction',
            name='inter_occupation3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inter_occupation2', to='team.Occupation_type'),
        ),
    ]
