# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-15 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0013_auto_20180515_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_num', models.IntegerField(primary_key=True, serialize=False)),
                ('mtr_lesson', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='mtr_daily_report',
            name='mtr_lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='team.State'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mtr_info',
            name='field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='team.Occupation_type'),
            preserve_default=False,
        ),
    ]
