# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-15 10:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0014_auto_20180515_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mtr_info',
            old_name='field',
            new_name='occ_num',
        ),
        migrations.RemoveField(
            model_name='mrapply',
            name='mrapply_start',
        ),
        migrations.AlterField(
            model_name='mrapply',
            name='mrapply_con',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.State'),
        ),
    ]
